// Copyright (c) 2015, FireBite/Aceticsoft Studios Inc.
// All rights reserved.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
// ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
// ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Decompiled by AS3 Sorcerer 1.99
// http://www.as3sorcerer.com/

//_060._rp

package _060 {
import flash.events.Event;

public class _rp extends Event {

    public static const UNDO_COMMAND_EVENT:String = "UNDO_COMMAND_EVENT";
    public static const REDO_COMMAND_EVENT:String = "REDO_COMMAND_EVENT";
    public static const CLEAR_COMMAND_EVENT:String = "CLEAR_COMMAND_EVENT";
    public static const LOAD_COMMAND_EVENT:String = "LOAD_COMMAND_EVENT";
    public static const SAVE_COMMAND_EVENT:String = "SAVE_COMMAND_EVENT";
    public static const TEST_COMMAND_EVENT:String = "TEST_COMMAND_EVENT";

    public function _rp(_arg1:String) {
        super(_arg1);
    }
}
}//package _060

